routes/web.php
<?php

use App\Http\Controllers\LinkShortener;
use App\Http\Livewire\Auth\Forget;
use App\Http\Livewire\Auth\Login;
use App\Http\Livewire\Auth\Register;
use App\Http\Livewire\Dashboard\Counter;
use App\Http\Livewire\Dashboard\Users\Create as UsersCreate;
use App\Http\Livewire\Dashboard\Users\Edit as UsersEdit;
use App\Http\Livewire\Dashboard\Users\Index as UsersIndex;
use App\Http\Livewire\Dashboard\Roles\Create as RolesCreate;
use App\Http\Livewire\Dashboard\Roles\Edit as RolesEdit;
use App\Http\Livewire\Dashboard\Roles\Index as RolesIndex;
use App\Http\Livewire\Dashboard\Categories\Create as CategoriesCreate;
use App\Http\Livewire\Dashboard\Categories\Edit as CategoriesEdit;
use App\Http\Livewire\Dashboard\Categories\Index as CategoriesIndex;
use App\Http\Livewire\Dashboard\Links\Create as LinksCreate;
use App\Http\Livewire\Dashboard\Links\Edit as LinksEdit;
use App\Http\Livewire\Dashboard\Links\Statistics as LinksStatistics;
use App\Http\Livewire\Dashboard\Links\Index as LinksIndex;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Route::middleware('guest')->group(function (){
    Route::get('login', Login::class)->name('login');
    Route::get('register', Register::class)->name('register');
    Route::get('forget', Forget::class)->name('forget');
});

Route::get('logout', function (){
    auth()->logout();
    return redirect('/');
})->middleware(['auth'])->name('logout');

Route::prefix('dashboard')->middleware('auth')->group(function (){
    Route::get('', Counter::class)->name('dashboard');
    Route::get('users', UsersIndex::class)->name('dashboard.users');
    Route::get('users/create', UsersCreate::class)->name('dashboard.users.create');
    Route::get('users/edit/{user}', UsersEdit::class)->name('dashboard.users.edit');

    Route::get('roles', RolesIndex::class)->name('dashboard.roles');
    Route::get('roles/create', RolesCreate::class)->name('dashboard.roles.create');
    Route::get('roles/edit/{role}', RolesEdit::class)->name('dashboard.roles.edit');

    Route::get('categories', CategoriesIndex::class)->name('dashboard.categories');
    Route::get('categories/create', CategoriesCreate::class)->name('dashboard.categories.create');
    Route::get('categories/edit/{category}', CategoriesEdit::class)->name('dashboard.categories.edit');

    Route::get('links', LinksIndex::class)->name('dashboard.links');
    Route::get('links/create', LinksCreate::class)->name('dashboard.links.create');
    Route::get('links/edit/{link}', LinksEdit::class)->name('dashboard.links.edit');
    Route::get('links/statistics/{link}', LinksStatistics::class)->name('dashboard.links.statistics');
});


Route::get('{link:slug}', [LinkShortener::class, 'redirect']);

app/Http/Livewire/Dashboard/Categories/CategoryBox.php
<?php

namespace App\Http\Livewire\Dashboard\Categories;

use App\Actions\Category\DeleteCategory;
use App\Models\Category as CategoryModel;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class CategoryBox extends Component
{
    use AuthorizesRequests;

    public CategoryModel $category;
    public int $index;

    public function delete()
    {
        $this->authorize('delete-categories');

        DeleteCategory::delete($this->category->id);

        $this->emitUp('categoryDeleted');
    }

    public function render()
    {
        return view('livewire.dashboard.category.category-box');
    }
}

app/Http/Livewire/Dashboard/Categories/Create.php
<?php

namespace App\Http\Livewire\Dashboard\Categories;

use App\Actions\Category\CategoryValidationRule;
use App\Actions\Category\CreateNewCategory;
use App\Actions\Role\CreateNewRole;
use App\Http\Livewire\Traits\WithToast;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Create extends Component
{
    use WithToast, CategoryValidationRule, AuthorizesRequests;

    public string $prefix = 'categoryArr.';
    public array $categoryArr;

    public function mount()
    {
        $this->authorize('create-categories');

        $this->categoryArr = [];
    }

    public function render()
    {
        return view('livewire.dashboard.category.create');
    }

    public function create()
    {
        $this->validate($this->categoryRulesForCreate($this->prefix));

        (new CreateNewCategory())->create($this->categoryArr);

        $this->toast(trans('toast.Successful category creation'));

        return redirect(route('dashboard.categories'));
    }
}

app/Http/Livewire/Dashboard/Categories/Edit.php
<?php

namespace App\Http\Livewire\Dashboard\Categories;

use App\Actions\Category\CategoryValidationRule;
use App\Actions\Category\UpdateCategory;
use App\Http\Livewire\Traits\WithToast;
use App\Models\Category;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Edit extends Component
{
    use CategoryValidationRule, WithToast, AuthorizesRequests;

    public string $prefix = 'categoryArr.';
    public array $categoryArr;

    public function mount(Category $category)
    {
        $this->authorize('update-categories');

        $this->categoryArr = $category->toArray();
    }

    public function render()
    {
        return view('livewire.dashboard.category.edit');
    }

    public function update()
    {
        $this->validate($this->categoryRulesForUpdate($this->categoryArr['id'], $this->prefix));

        (new UpdateCategory())->update($this->categoryArr['id'], $this->categoryArr);

        $this->toast(trans('toast.Successful category updated'));

        return redirect(route('dashboard.categories'));
    }
}

app/Http/Livewire/Dashboard/Categories/Index.php
<?php

namespace App\Http\Livewire\Dashboard\Categories;

use App\Http\Livewire\Traits\WithToast;
use App\Models\Category as CategoryModel;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination, WithToast, AuthorizesRequests;

    public $search;

    protected $listeners = ['categoryDeleted' => 'categoryDelete'];

    public function mount()
    {
        $this->authorize('show-categories');
    }

    public function render()
    {
        return view('livewire.dashboard.category.index', [
            'categories' => CategoryModel::where('title', 'LIKE', '%' . $this->search . '%')
                ->orWhere('slug', 'LIKE', '%' . $this->search . '%')
                ->orWhere('description', 'LIKE', '%' . $this->search . '%')
                ->latest()
                ->paginate(10),
        ]);
    }

    public function categoryDelete()
    {
        $this->toast(trans('toast.Successful category removal'), true);
    }
}

app/Http/Livewire/Dashboard/Counter.php
<?php

namespace App\Http\Livewire\Dashboard;

use Livewire\Component;

class Counter extends Component
{
    public function render()
    {
        return view('livewire.dashboard.counter');
    }
}

app/Http/Livewire/Dashboard/Links/Create.php
<?php

namespace App\Http\Livewire\Dashboard\Links;

use App\Actions\Category\CreateNewCategory;
use App\Actions\Link\CreateNewLink;
use App\Actions\Link\LinkValidationRule;
use App\Http\Livewire\Traits\WithToast;
use App\Models\Category;
use App\Models\Link;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;
use function Composer\Autoload\includeFile;

class Create extends Component
{
    use WithToast, LinkValidationRule, AuthorizesRequests;

    public string $prefix = 'linkArr.';
    public array $linkArr;

    public function mount()
    {
        $this->authorize('create-links');

        $this->linkArr = [];
        $this->linkArr['is_active'] = true;
        $this->linkArr['code'] = 302;
        $this->linkArr['category_id'] = null;
        $this->linkArr['slug'] = $this->generateRandomStr();
    }

    public function render()
    {
        return view('livewire.dashboard.links.create', [
            'categories' => Category::all()
        ]);
    }

    private function generateRandomStr()
    {
        do {
            $str = \Str::random(6);
        } while (!! Link::where('slug', $str)->first());

        return $str;
    }

    public function create()
    {
        $this->validate($this->linkRulesForCreate($this->prefix));

        (new CreateNewLink())->create($this->linkArr);

        $this->toast(trans('toast.Successful link creation'));

        return redirect(route('dashboard.links'));
    }
}

app/Http/Livewire/Dashboard/Links/Edit.php
<?php

namespace App\Http\Livewire\Dashboard\Links;

use App\Actions\Link\CreateNewLink;
use App\Actions\Link\LinkValidationRule;
use App\Actions\Link\UpdateLink;
use App\Http\Livewire\Traits\WithToast;
use App\Models\Category;
use App\Models\Link;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Edit extends Component
{
    use WithToast, LinkValidationRule, AuthorizesRequests;

    public string $prefix = 'linkArr.';
    public array $linkArr;

    public function mount(Link $link)
    {
        $this->authorize('update-links');

        $this->linkArr = $link->toArray();
    }

    public function render()
    {
        return view('livewire.dashboard.links.edit', [
            'categories' => Category::all()
        ]);
    }

    public function update()
    {
        $this->validate($this->linkRulesForUpdate($this->linkArr['id'], $this->prefix));

        (new UpdateLink())->update($this->linkArr['id'], $this->linkArr);

        $this->toast(trans('toast.Successful link updated'));

        return redirect(route('dashboard.links'));
    }
}

app/Http/Livewire/Dashboard/Links/Index.php
<?php

namespace App\Http\Livewire\Dashboard\Links;

use App\Http\Livewire\Traits\WithToast;
use App\Models\Link as LinkModel;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination, WithToast, AuthorizesRequests;

    public $search;

    protected $listeners = ['linkDeleted' => 'linkDelete'];

    public function mount()
    {
        $this->authorize('show-links');
    }

    public function render()
    {
        return view('livewire.dashboard.links.index', [
            'links' => LinkModel::where('title', 'LIKE', '%' . $this->search . '%')
                ->orWhere('slug', 'LIKE', '%' . $this->search . '%')
                ->orWhere('description', 'LIKE', '%' . $this->search . '%')
                ->orWhere('destination', 'LIKE', '%' . $this->search . '%')
                ->latest()
                ->paginate(10),
        ]);
    }

    public function linkDelete()
    {
        $this->toast(trans('toast.Successful link removal'), true);
    }
}

app/Http/Livewire/Dashboard/Links/LinkBox.php
<?php

namespace App\Http\Livewire\Dashboard\Links;

use App\Actions\Category\DeleteCategory;
use App\Actions\Link\DeleteLink;
use App\Models\Link as LinkModel;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class LinkBox extends Component
{
    use AuthorizesRequests;

    public LinkModel $link;
    public int $index;

    public function delete()
    {
        $this->authorize('delete-links');

        DeleteLink::delete($this->link->id);

        $this->emitUp('linkDeleted');
    }

    public function render()
    {
        return view('livewire.dashboard.links.link-box');
    }
}

app/Http/Livewire/Dashboard/Links/Statistics.php
<?php

namespace App\Http\Livewire\Dashboard\Links;

use App\Models\Link;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Statistics extends Component
{
    use AuthorizesRequests;

    public Link $link;
    public $statistics;
    public $period;

    public function mount(Link $link)
    {
        $this->authorize('statistics-links');

        $this->link = $link;
        $this->statistics = 'browser';
        $this->period = 1;
    }

    public function render()
    {
        return view('livewire.dashboard.links.statistics');
    }

    public function update()
    {
        $statistics = $this->link->statistics()->where('created_at', '>', now()->subDays($this->period)->toDateTimeString())->get(["agent->$this->statistics as $this->statistics"]);
        $datasets = $statistics->groupBy($this->statistics)->map(function ($dataset){
            return $dataset->count();
        })->toArray();

        $datasetsArr = [
            'label' => trans('statistics.browser'),
            'keys' => array_keys($datasets),
            'values' => array_values($datasets),
        ];

        $this->dispatchBrowserEvent('chartjs', $datasetsArr);
    }
}

app/Http/Livewire/Dashboard/Roles/Create.php
<?php

namespace App\Http\Livewire\Dashboard\Roles;

use App\Actions\Role\CreateNewRole;
use App\Actions\Role\RoleValidationRule;
use App\Http\Livewire\Traits\WithToast;
use App\Models\Permission;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Create extends Component
{
    use WithToast, RoleValidationRule, AuthorizesRequests;

    public string $prefix = 'roleArr.';
    public array $roleArr;

    public function mount()
    {
        $this->authorize('create-roles');

        $this->roleArr = [];
    }

    public function render()
    {
        return view('livewire.dashboard.roles.create', [
            'permissions' => Permission::all()
        ]);
    }

    public function create()
    {
        if (isset($this->roleArr['permissions']))
            $this->roleArr['permissions_keys'] = array_keys($this->roleArr['permissions'], true);

        $this->validate($this->roleRulesForCreate($this->prefix));

        (new CreateNewRole())->create($this->roleArr);

        $this->toast(trans('toast.Successful role creation'));
        return redirect(route('dashboard.roles'));
    }
}

app/Http/Livewire/Dashboard/Roles/Edit.php
<?php

namespace App\Http\Livewire\Dashboard\Roles;

use App\Actions\Role\RoleValidationRule;
use App\Actions\Role\UpdateRole;
use App\Http\Livewire\Traits\WithToast;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Edit extends Component
{
    use RoleValidationRule, WithToast, AuthorizesRequests;

    public string $prefix = 'roleArr.';
    public array $roleArr;

    public function mount(Role $role)
    {
        $this->authorize('update-roles');

        $this->roleArr = $role->toArray();

        foreach ($role->permissions as $permission)
            $this->roleArr['permissions'][$permission->id] = true;

    }

    public function render()
    {
        return view('livewire.dashboard.roles.edit', [
            'permissions' => Permission::all()
        ]);
    }

    public function update()
    {
        if (isset($this->roleArr['permissions']))
            $this->roleArr['permissions_keys'] =  array_keys($this->roleArr['permissions'], true);

        $this->validate($this->roleRulesForUpdate($this->roleArr['id'], $this->prefix));

        (new UpdateRole())->update($this->roleArr['id'], $this->roleArr);

        $this->toast(trans('toast.Successful role updated'));
        return redirect(route('dashboard.roles'));
    }
}

app/Http/Livewire/Dashboard/Roles/RoleBox.php
<?php

namespace App\Http\Livewire\Dashboard\Roles;

use App\Actions\Role\DeleteRole;
use App\Models\Role as RoleModel;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class RoleBox extends Component
{
    use AuthorizesRequests;

    public RoleModel $role;
    public int $index;

    public function delete()
    {
        $this->authorize('delete-roles');

        DeleteRole::delete($this->role->id);
        $this->emitUp('roleDeleted');
    }

    public function render()
    {
        return view('livewire.dashboard.roles.role-box');
    }
}

app/View/Components/Box.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Box extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(
        public string $name
    ){ }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.boxes.'.$this->name);
    }
}

app/View/Components/Button.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Button extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(
        public string $type
    ){ }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.buttons.'.$this->type);
    }
}

app/View/Components/Input.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Input extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(
        public string $type
    ){}

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.inputs.'.$this->type);
    }
}

resources/views/livewire/dashboard/users/create.blade.php
<x-box name="dashboard-content" :title="__('heading.Add User')">
    <x-form wire:submit.prevent="create" class="w-full">
        <section class="flex flex-col sm:flex-row sm:space-x-reverse sm:space-x-3">
            <x-input :name="$prefix.'first_name'" type="text" maxlength="40" autofocus>
                {{ __('label.first_name') }}
            </x-input>
            <x-input :name="$prefix.'last_name'" type="text" maxlength="60">
                {{ __('label.last_name') }}
            </x-input>
            <x-input class="ltr text-left" :name="$prefix.'email'" type="email" maxlength="255">
                {{ __('label.email') }}
            </x-input>
        </section>
        <section class="flex flex-col sm:flex-row sm:space-x-reverse sm:space-x-3">
            <x-input class="ltr text-left" :name="$prefix.'phone_number'" type="tel" maxlength="11">
                {{ __('label.phone_number') }}
            </x-input>
            <x-input class="ltr text-left" :name="$prefix.'password'" type="password">
                {{ __('label.password') }}
            </x-input>
            <div class="w-full">
                <select class="form-select" aria-label="{{ __('label.role') }}" wire:model.defer="{{ $prefix.'role_id' }}">
                    <option value="" selected>{{ __('label.no_role') }}</option>
                    @foreach($roles as $role)
                        <option value="{{ $role->id }}">{{ $role->name }}</option>
                    @endforeach
                </select>
                <x-error :name="$prefix.'role_id'" />
            </div>
        </section>
        <div class="flex justify-between items-center">
            <x-button class="form-button-primary form-button-small !mb-0 !w-24 max-w-full" type="submit" form="create">
                {{ __('button.Add') }}
            </x-button>
            <a class="button-link button-link-secondary" href="{{ route('dashboard.users') }}">
                {{ __('link.back') }}
            </a>
        </div>
    </x-form>
</x-box>

resources/views/livewire/dashboard/users/edit.blade.php
<x-box name="dashboard-content" :title="__('heading.Edit User')">
    <x-form wire:submit.prevent="update" class="w-full">
        <section class="flex flex-col sm:flex-row sm:space-x-reverse sm:space-x-3">
            <x-input :name="$prefix.'first_name'" type="text" maxlength="40" autofocus>
                {{ __('label.first_name') }}
            </x-input>
            <x-input :name="$prefix.'last_name'" type="text" maxlength="60">
                {{ __('label.last_name') }}
            </x-input>
        </section>
        <section class="flex flex-col sm:flex-row sm:space-x-reverse sm:space-x-3">
            <x-input class="ltr text-left" :name="$prefix.'phone_number'" type="tel" maxlength="11">
                {{ __('label.phone_number') }}
            </x-input>
            <x-input class="ltr text-left" :name="$prefix.'email'" type="email" maxlength="255">
                {{ __('label.email') }}
            </x-input>
            <div class="w-full">
                <select class="form-select" aria-label="{{ __('label.role') }}" wire:model.defer="{{ $prefix.'role_id' }}">
                    <option value="" selected>{{ __('label.no_role') }}</option>
                    @foreach($roles as $role)
                        <option value="{{ $role->id }}">{{ $role->name }}</option>
                    @endforeach
                </select>
                <x-error :name="$prefix.'role_id'" />
            </div>
        </section>
        <div class="flex justify-between items-center">
            <x-button class="form-button-primary form-button-small !mb-0 !w-24 max-w-full" type="submit" form="update">
                {{ __('button.Update') }}
            </x-button>
            <a class="button-link button-link-secondary" href="{{ route('dashboard.users') }}">
                {{ __('link.back') }}
            </a>
        </div>
    </x-form>
</x-box>

resources/views/livewire/dashboard/users/index.blade.php
<x-box name="dashboard-content" :title="__('heading.Users')">
    @can('create-users')
        <x-slot:header-icon>
            <a href="{{ route('dashboard.users.create') }}">
                <svg class="icon w-6 h-6 !stroke-primary-500">
                    <use xlink:href="#add"/>
                </svg>
            </a>
        </x-slot:header-icon>
    @endcan
    <x-slot:header-search class="test">
        <x-input name="search" model="debounce.250ms" type="text" maxlength="255">
            {{ __('label.search') }}
        </x-input>
    </x-slot:header-search>
    <table class="w-full">
        <thead class="text-primary-500 bg-primary-50">
        <tr>
            <th scope="col" class="px-6 py-3 text-center">
                {{ __('table.#') }}
            </th>
            <th scope="col" class="px-6 py-3">
                {{ __('table.First Name') }}
            </th>
            <th scope="col" class="px-6 py-3">
                {{ __('table.Last Name') }}
            </th>
            <th scope="col" class="px-6 py-3 text-center">
                {{ __('table.Phone Number') }}
            </th>
            <th scope="col" class="px-6 py-3 text-center">
                {{ __('table.Role') }}
            </th>
            <th scope="col" class="px-6 py-3 text-center">
                {{ __('table.Actions') }}
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $index => $user)
            <livewire:dashboard.users.user-box :user="$user" :index="$users->firstItem() + $index" :wire:key="$user['id']">
        @endforeach
        </tbody>
    </table>
    {{ $users->links() }}
</x-box>
{{--<div>

</div>--}}

resources/views/livewire/dashboard/users/user-box.blade.php
<tr class="bg-white">
    <th scope="row" class="px-6 py-4 text-center">
        {{ $index }}
    </th>
    <td class="px-6 py-4">
        {{ $user->first_name }}
    </td>
    <td class="px-6 py-4">
        {{ $user->last_name }}
    </td>
    <td class="px-6 py-4 text-center">
        {{ $user->phone_number }}
    </td>
    <td class="px-6 py-4 text-center">
        {{ $user->roles()->first()->name ?? '' }}
    </td>
    <td class="px-6 py-4 flex justify-center items-center space-x-reverse space-x-1">
        @can('update-users')
            <a href="{{ route('dashboard.users.edit', ['user' => $user->id]) }}">
                <svg class="icon w-6 h-6">
                    <use xlink:href="#edit"/>
                </svg>
            </a>
        @endcan
        @can('delete-users')
            <button type="button" wire:click="delete">
                <svg class="icon w-6 h-6 hover:stroke-red-500">
                    <use xlink:href="#delete"/>
                </svg>
            </button>
        @endcan
    </td>
</tr>